class APIAnswerError(Exception):
    """Ошибка при незапланированной работе API."""
    pass
